### ISSUE TITLE
In streaming mode social-distancing.py gets terminated by an error

### ISSUE THREAD

**Issue by bpogorelc** [IIT-PAVIS/Social-Distancing#14]
Hi,

When using streaming mode with the following parameters (streaming='enabled', video='enabled', image='disabled', preview='disabled', etc.) and the RTSP from a network camera, many times the execution of the social-distancing.py gets terminated by some error after an arbitrary time of running, i.e., from 1 second up to 10 hours and in three different ways:
1.	without any error printed on the terminal
2.	error like "[h264 @ 0x55d380821600] error while decoding MB 41 30, bytestream -17" on the terminal
3.	the following printed on the terminal (rarely):
[NULL @ 0x55f60ce2e100] missing picture in access unit with size 159
[h264 @ 0x55f60ce7a240] no frame!

Could you please suggest what can I do to prevent the social-distancing.py to get terminated by an error?

Many thanks in advance!!!

**Comment by mayaghaei** [comment]
Hi,
all these errors seem to me are caused due to incorrect/missing input from the camera? we have little information in your case to be able to actually help solving your problem. but if the problem rarely happens and if only one frame is not too important to you, you probably can skip processing that frame?
